### ISSUE TITLE
Invalid RSS

### ISSUE THREAD

**Issue by mtsz-pl** [kevinboone/kevinboone.github.io#1]
Hello @kevinboone 

I wanted to add your blog's RSS to the reader, but there is some issue around `image` and `lastBuildDate` tags in https://github.com/kevinboone/kevinboone.github.io/blob/main/feed.xml:

```xml
...
<lastBuildDate>
<image>
<title>Kevin Boone's website</title>
<link>https://kevinboone.me</link>
<url>https://kevinboone.me/img/favicon.ico</url>
</image>Mon, November 04 2024</lastBuildDate>
...
```

Also, W3C validator point this out: https://www.feedvalidator.org/check.cgi?url=https%3A%2F%2Fkevinboone.me%2Ffeed.xml

I would be much obliged if you could fix that. I really like reading your blog.

**Comment by kevinboone** [comment]
Hi

Thanks for bringing this issue to my attention. Unfortunately, feedvalidator.org is currently not working, so I can't see the problem you describe. If you can give me any more information, please do. Otherwise I'll look into it when feedvalidator.org is working again.

Best wishes
Kevin

**Comment by mtsz-pl** [comment]
https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fkevinboone.github.io%2Ffeed.xml

It looks like the opening for `lastBuildDate` tag moved above `image` tag, below is possible fix for that.

<img width="1291" alt="Zrzut ekranu 2024-11-22 o 11 35 50" src="https://github.com/user-attachments/assets/19d55eb0-6c4b-4207-8763-ee13bdae29cf">

Also, it looks like dates in all entries are not compliant with RFC-822, so RSS readers have problems with parsing that. In my reader, I get 1 Jan 1 (January 1st of year 1) for each entry.

**Comment by kevinboone** [comment]
Hi

Well, I fixed the XML formatting error (sorry). But I still get validation errors. I modified the dates to match what I _think_ RFC-822 requires, but the validator still complains. It complains, for example, if I say "Mon 05" rather than "Mon 5", but my reading of the RFC suggests that the day-of-month should be two digits. Also, it complains that there are HTML tags in titles, but they've come directory from the HTML, so stripping the tags would be irritating. 

I'd be interested to know whether this works any better for you.

Best wishes
Kevin

**Comment by mtsz-pl** [comment]
Hi @kevinboone

looks like dates issue is fixed, at least for the reader I use (NetNewsWire) - thanks for that!

I'm not expert on RSS, but from what I read, it is a good practice to wrap any HTML in XML file with CDATA tag - it helps XML file readers differentiate between proper XML and non-XML special characters. Some of the blogs I subsribe to wrap titles and descriptions with CDATA. Reference: https://support.google.com/webmasters/thread/284147525/can-we-use-cdata-in-title-tag-rss-feed?hl=en

But NetNewsWire actually works perfectly with your feed now, so as for me, it's perfect! Thank you again. I will close the issue.
